// Port of DCourt/Static/Rumors.java and DCourt/Static/GRumors.java

export const rumors = [
  "They sez as Aileen Suitor is lookin' fer a husband.",
  'I heard Bill Smith used to be in the Dragon Guard.',
  'Silas Keeper is a decent sort, when sober.',
  'They sez Sally Trader gives ye a fair price.',
  'I heard that Fenton Magus eats small children.',
  'That Elden Bishop is a funny sort.',
  'Half of what these people tell ya are dead lies.',
  "The Queen is always lookin' for new Guardsmen.",
  "There's this little dwarf smithy out in the woods.",
  'I saw this strange cave in the woods.',
  "Be careful you don't end up in the Castle Dungeons.",
  'There is a dragon deep in the Abandoned Mines.',
  'Beware the wyverns, they steal your soul.',
  'Donatin to the healer just makes ya poor.',
  'Donatin to the healer is good fer the soul.',
  "Centaurs ain't a bad sort, just don't cross 'em.",
  'Watch them rats, them is filthy little buggers.',
  "Rats'll make yez sick.",
  "Be careful of mages, they have dyin' curses.",
  'Beware the curse of the wizard.',
  'Goblins ken be dengrous, if you bin drinkin. Hic.',
  'Never trust a gypsy.',
  "A little food can be handy for handlin' rats.",
  "It's hard getting' to the woods.",
  "If ye ever git to th' castle, stay outa the dunjin.",
  'Salves are great for really long fights.',
  'I hear that potions give you lots of energy.',
  "Like this knife? It's been enchanted.",
  'The queen is hundreds of years old...',
  'They call it the Arcane Forest.',
  "There's big ugly giants in the mountains.",
  "I've been to the mountains.  It's a long trip.",
  'Harpy wounds can fester up badly.',
  'Elves are uppity critters, but they will trade.',
  "There's another trader up in the mountains.",
  'I saw a troll under a bridge once.  Mean booger.',
  'I think maybe Fenton Magus knows a secret or two.',
  "They ain't no food in the mountains.  I bin there.",
]

export const grumors = [
  'Whyz you herzez human?  You likezez to die?',
  'Only tough humanzez come inzide of the Mound.',
  "You need zome inzurancez.  Good againzt thievin'",
  "Inzurancezez keepz the thievez out.",
  'I hear mapzez takez you placez.',
  'Buy zome mapz to zee the under-worldzez.',
  'I live inzide of the warrenzez.',
  'The warrenzez iz a homey little plaze.',
  "Don' go to the warrenzez! *phew*",
  "Don' go to the warrenzez! (human zcum)",
  'The Treazury haz lotz of good ztuff.',
  'Go to the Treazury for to get the goldzez.',
  'The Thronzez Room haz Herozez, Championzez, and Knightzez.',
  "I never been to the Thronzez Room.  High falutin'.",
  'You needzez a map to getzez to the Thronez Room.',
  'Wormzez are juzt zweethartz.  Give em foodzez.',
  'Wormzez likez to eatz minerz capzez.',
  'I hear that thievez like to zell you fake turnipz.',
  "Bewarezez of the Zwindlerz.  Pretend to tradezez.",
  "Don' go fightin' berzerkezez.  Give em foodzez.",
  "Fanaticzez are juzt warmin' up.  Gotta blind'em.",
  'I hear thez Queen iz lookin fer matzez',
  "The Queenz Championzez are friggin' nutzez.",
  'Queenzez zuck your brainzez.',
  'Look out for Magezez.  They mezz with you brainzez.',
  'Wizardez makez you do thingzez you don wantz to.',
  'Itz hard diggin tunnelz.  Zome goblinz get kilt!',
  'If you zee a gang, theyz juzt diggin tunnelz.',
  'HEY! Goblinzez got heroz too!',
  "You zee a hero, youz better runz human...",
  'Championzez got flaming bladezez!  Rock Hard!',
]
